const express = require("express");
const router = express.Router();
const Programme_controller = require("../../controller/programme");
router.get("/", Programme_controller.get);
router.get("/getweb", Programme_controller.getweb);
router.get("/sort/:event", Programme_controller.sortbydate);
router.get("/byevent/:event", Programme_controller.getprogrammebyevent);
router.post("/create", Programme_controller.create);
router.delete("/delete/:id", Programme_controller.delete);
router.put("/update/:programmeId", Programme_controller.updateProgramme);
module.exports = router;
